Добавлены файлы программы для оценки марком
Ivanstarterprog/SquareMatrix pull request #2
Opened 2024-02-23 09:53 UTC by Ivanstarterprog

2024-02-23 09:55 UTC, Hamjoshua commented
Одобрено

2024-02-26 01:40 UTC, Silmarill requested changes
Need corrections.

2024-02-26 01:40 UTC, Silmarill commented on SquareMatrix/Program.cs
> +                for (int rowIndex = 0; rowIndex < sideSize; ++rowIndex)
лучше отделять смысловые блоки пустой строкой для повышения читаемости

2024-02-26 01:40 UTC, Silmarill commented on SquareMatrix/Program.cs
> +            SquareMatrix test = new SquareMatrix(4);
Я разочарован именем переменной.

2024-02-26 01:40 UTC, Silmarill commented on SquareMatrix/Program.cs
> +            SquareMatrix test2 = new SquareMatrix(4);
Я разочарован именем переменной 2.

2024-02-26 01:40 UTC, Silmarill commented on SquareMatrix/Program.cs
> +            SquareMatrix test3 = new SquareMatrix(5);
Я разочарован именем переменной 3

2024-02-26 01:40 UTC, Silmarill commented on SquareMatrix/Program.cs
> +            clonedMatrix.matrix = matrix;
Нужно обоснование, что копирование здесь - глубокое.

2024-02-26 01:40 UTC, Silmarill commented on SquareMatrix/Program.cs
> +        static void Main(string[] args)
Не увидел само клонирование.

2024-02-29 05:10 UTC, Hamjoshua requested changes
Отправлено на переработку

2024-02-29 05:10 UTC, Hamjoshua commented on SquareMatrix/Program.cs
> +        private int sideSize { get; set; }
Приватные поля и свойства должны оформляться так: _camelCase

2024-02-29 05:10 UTC, Hamjoshua commented on SquareMatrix/Program.cs
> +        static Random RandomInt = new Random();
Статические приватные поля должны оформляться так: st_camelCase

2024-02-29 05:10 UTC, Hamjoshua commented on SquareMatrix/Program.cs
> +        public object Clone()
Это копирование не глубокое

2024-02-29 05:10 UTC, Hamjoshua commented on SquareMatrix/Program.cs
> +                    int ColumnNumber = minor * squareMatrix.matrix[0, columnIndex];
Все переменные должны быть либо с большой буквы, либо с маленькой. В твоем коде доминируют camelCase

2024-02-29 05:10 UTC, Hamjoshua commented on SquareMatrix/Program.cs
> +                    int ColumnNumber = minor * squareMatrix.matrix[0, columnIndex];
Следовательно, все переменные должны быть в camelCase

2024-02-29 05:10 UTC, Hamjoshua commented on SquareMatrix/Program.cs
> +                comparedMatrixWeight = 0;
Разделяй смысловые блоки Ентером для улучшения читаемости

2024-02-29 09:14 UTC, Hamjoshua approved these changes

2024-02-29 09:15 UTC, merged